### ISSUE TITLE
Assertion failed: Could not find the input listener to remove

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer-two-variables#2]
CT fuzz error:

equality-explorer-two-variables : fuzz : require.js : run
Uncaught Error: Assertion failed: Could not find the input listener to remove
Error: Assertion failed: Could not find the input listener to remove
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1527221200212/assert/js/assert.js:22:13)
    at Touch.removeInputListener (https://bayes.colorado.edu/continuous-testing/snapshot-1527221200212/scenery/js/input/Pointer.js?bust=1527226005129:152:17)
    at SeparateTermsDragListener.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1527221200212/scenery/js/input/SimpleDragHandler.js?bust=1527226005129:224:20)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1527221200212/scenery/js/input/SimpleDragHandler.js?bust=1527226005129:109:16)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1527221200212/scenery/js/input/Input.js?bust=1527226005129:1345:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1527221200212/scenery/js/input/Input.js?bust=1527226005129:1301:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1527221200212/scenery/js/input/Input.js?bust=1527226005129:1069:12)
    at Input.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1527221200212/scenery/js/input/Input.js?bust=1527226005129:672:14)
    at InputFuzzer.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1527221200212/scenery/js/input/InputFuzzer.js?bust=1527226005129:246:27)
    at InputFuzzer.touchEndAction (https://bayes.colorado.edu/continuous-testing/snapshot-1527221200212/scenery/js/input/InputFuzzer.js?bust=1527226005129:61:12)
Approximately 5/24/2018, 10:06:40 PM

**Comment by pixelzoom** [comment]
@jonathanolson It looks like this is failing while touch fuzzing, and it's failing in SimpleDragHandler `endDrag`, line 224:

```js
    endDrag: function( event ) {
      if ( !this.dragging ) { return; }

      this.pointer.dragging = false;
      this.pointer.cursor = null;
224   this.pointer.removeInputListener( this.dragListener );
```

I'm not doing anything with `this.pointer` (treating it as `@private`) so I suspect that this may be related to either the fix you made for https://github.com/phetsims/equality-explorer/issues/97, or other recent scenery changes.

**Comment by pixelzoom** [comment]
Looking through SimpleDragHandler, I see `this.pointer.removeInputListener( this.dragListener )` called in 2 places: `endDrag` and `dispose`.   What's probably happening is that my model element (`Term`) is being disposed during the drag cycle, before `endDrag` is called.  Using the PhET creator pattern, that causes its associated `TermNode` to be disposed, which disposes of the drag handler.    So perhaps the best way to address this would be:

```js
    endDrag: function( event ) {
      if ( !this.dragging ) { return; }

      this.pointer.dragging = false;
      this.pointer.cursor = null;
224   if ( this.pointer.hasInputListener( this.dragListener ) ) {
        this.pointer.removeInputListener( this.dragListener ); 
      }
```

**Comment by pixelzoom** [comment]
Looking closer at `dispose`, I think there's some faulty logic here.  Is it callable during a drag cycle or not?  In either case, the implementation is lacking.

If `dispose` is _not_ callable during a drag cycle, there's no documentation to that affect.  And I would expect to see an assertion like `assert && assert( !this.dragging, ... );`

If dispose _is_ callable during a drag cycle, I would expect to see a call to `interrupt`, and a check for `this.pointer.hasInputListener`.

**Comment by pixelzoom** [comment]
Above I said:
> What's probably happening is that my model element (`Term`) is being disposed during the drag cycle ...

I inspected my SimpleDragHandler type hierarchy (TermDragListener, SeparateTermsDragListener, CombinedTermsDragListener), and all calls to Term `dispose` happen after SimpleDragHandler `options.end` has been called.

**Comment by jonathanolson** [comment]
Investigating.

**Comment by jonathanolson** [comment]
It would be helpful for me to collaborate on this a bit, or to learn/review the structure of your input handling here.

One reproduction is showing a trace of:
```
[Input] touchEnd('862',44,69 4069.599999987986 touchend);
| [Input] upEvent Touch#862 changed:false
| | [Input] branchChangeEvents: Touch#862 sendMove:false
| | [EventDispatch] up trail:[Trail  6] pointer:Touch#862 at Vector2(44, 69)
| | | [EventDispatch] up
| | | | [InputListener] DownUpListener (pointer) up for [Trail 0.1.1 6-96-307-306]
| | | | | [InputListener] DownUpListener buttonUp
| | | | | | [Pointer] removeInputListener to Touch#862
| | | | | | [InputListener] SimpleDragHandler dispose
| | | | | | [InputListener] SimpleDragHandler dispose
| | | | | | | [Pointer] removeInputListener to Touch#862
| | | | | | [InputListener] SimpleDragHandler dispose
| | | | | | [InputListener] SimpleDragHandler dispose
| | | | | | [InputListener] SimpleDragHandler dispose
| | | | | | [InputListener] SimpleDragHandler dispose
| | | [EventDispatch] up
| | | | [InputListener] SimpleDragHandler (pointer) up for [Trail 0.1.3.1.1 6-96-307-173-172-171]
| | | | | [InputListener] SimpleDragHandler endDrag
| | | | | | [Pointer] removeInputListener to Touch#862
```

where it looks like `lockedProperty` being changed is disposing LOTS of SimpleDragHandlers. There are two listeners added to the pointer in question (DownUpListener for the LockControl, and a SimpleDragHandler for an HBox under a TermsToolbox), and it's the 2nd one that, when firing, causes the error.

Since there are lots of different listeners, I'll probably temporarily hack a way of giving them unique IDs so I can trace down the removal more accurately.

**Comment by pixelzoom** [comment]
When the lock changes state, any terms that are not on the scale are disposed.  This includes terms that are being dragged (likely where this problem is occurring), and terms that are animating.

**Comment by pixelzoom** [comment]
As expected, this issue isn't specific to equality-explorer-two-variables.  CT shows the same failure for equality-explorer, and will eventually for equality-explorer-basics.

**Comment by pixelzoom** [comment]
I don't have an iPad with me to verify, but I would expect to be able to reproduce with the following steps:

1. Start Equality Explorer on a touch device.
2. Go to the Numbers screen.
3. With one finger, drag a '1' out of a toolbox. Do not release it.
4. With another finger, click on the lock toggle.

Clicking on the lock will dispose of the '1' that you're dragging while the drag is in progress.

**Comment by jonathanolson** [comment]
Collaborated fix pushed above (aqua/snapshots/unit tests passing).

**Comment by pixelzoom** [comment]
Seems to be working for EqEx. Closing.
