### ISSUE TITLE
create auxiliary screenshots

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/equality-explorer-two-variables#3]
From #1

**Comment by phet-steele** [comment]
@KatieWoe please take this screenshot and follow the naming scheme from other sims:
![image](https://user-images.githubusercontent.com/5863899/48167870-63b62800-e2aa-11e8-8445-a8febedc1f7a.png)

**Comment by KatieWoe** [comment]
@amanda-phet 
![equality-explorer-two-variables-screenshot-alt1](https://user-images.githubusercontent.com/41024075/48214885-2d29ed00-e33e-11e8-8c4f-37678ada55e6.png)

**Comment by amanda-phet** [comment]
Looks good. Thanks!

**Comment by KatieWoe** [comment]
Done
